- Move to using #!/usr/bin/env in the shebang so the location of where php, bash are installed does not matter anymore - Don't rely on the exact path of external commands like openssl and xmllint, as long as they are in your path it's OK - Add some JSON / JWT related filters - List all the dependencies in the installation instructions

diff --git a/Format XML b/Format XML
--- a/Format XML
+++ b/Format XML
@@ -1,10 +1,12 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # IN: XML
 # OUT: XML (reformatted)
 
-if [ "`which xmllint`" == "" ]; then
-    echo "Could not find xmllint in path"
+# Check is xmllint is available
+if ! command -v xmllint &> /dev/null
+then
+    echo "xmllint could not be found"
     exit 1
 fi
 
diff --git a/PEM X509 Decode b/PEM X509 Decode
--- a/PEM X509 Decode
+++ b/PEM X509 Decode
@@ -1,11 +1,13 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # IN: X.509 certificate in PEM format
 # OUT: Decoded certificate (using openssl)
 
-if [ ! -x /usr/bin/openssls ]; then
-    echo "Could not find /usr/bin/openssl"
+# Check if openssl is available
+if ! command -v openssl &> /dev/null
+then
+    echo "openssl could not be found"
     exit 1
 fi
 
-/usr/bin/openssl x509 -inform PEM -text -fingerprint
+openssl x509 -inform PEM -text -fingerprint
