Show error when required tool cannot be found

diff --git a/Format XML b/Format XML
--- a/Format XML
+++ b/Format XML
@@ -3,4 +3,9 @@
 # IN: XML
 # OUT: XML (reformatted)
 
+if [ "`which xmllint`" == "" ]; then
+    echo "Could not find xmllint in path"
+    exit 1
+fi
+
 xmllint --c14n - | XMLLINT_INDENT=$'\t' xmllint --encode UTF-8 --format -
diff --git a/PEM X509 Decode b/PEM X509 Decode
--- a/PEM X509 Decode
+++ b/PEM X509 Decode
@@ -3,4 +3,9 @@
 # IN: X.509 certificate in PEM format
 # OUT: Decoded certificate (using openssl)
 
+if [ ! -x /usr/bin/openssls ]; then
+    echo "Could not find /usr/bin/openssl"
+    exit 1
+fi
+
 /usr/bin/openssl x509 -inform PEM -text -fingerprint
